name: 'sptrans'
version: '1.0.0'
profile: 'sptrans'

model-paths: ['models']
target-path: 'target'
clean-targets: ['target']

models:
  sptrans:
    bronze:
      +schema: bronze
      +materialized: view
    silver:
      +schema: silver
      +materialized: table
    gold:
      +schema: gold
      +materialized: table