version: 2

models:
  - name: linhas
    description: "Tabela silver com informações das linhas da zona sul"
    columns:
      - name: codigo_linha
        description: "Código identificador da linha"
        tests:
          - not_null
          - unique
      - name: localizacao
        description: "Localização da linha"
        tests:
          - not_null
      - name: sentido_linha
        description: "Sentido da linha (1 ou 2)"
      - name: itinerario
        description: "Itinerário da linha"
      - name: tipo
        description: "Tipo da linha"