


FROM apache/airflow:2.7.1

USER airflow

COPY requirements.txt /requirements.txt

# Use constraints para garantir compatibilidade
ENV AIRFLOW_VERSION=2.7.1
ENV PYTHON_VERSION=3.8
ENV CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"

RUN pip install --no-cache-dir -r /requirements.txt -c "${CONSTRAINT_URL}"
