version: 2

models:
  - name: linhas_zona_sul
    description: "Tabela Bronze com dados brutos das linhas da Zona Sul"
    columns:
      - name: cl
        description: "Código da linha"
        tests:
          - not_null
      - name: lt
        description: "Letreiro da linha"
      - name: tp
        description: "Tipo da linha"
      - name: ts
        description: "Sentido da linha"